language: java

jdk:
  - openjdk8
  - openjdk9

matrix:
  allow_failures:
    - jdk: openjdk9

branches:
  only:
    - master
    - 1.0

after_success:
  - mvn clean test -Pcoveralls jacoco:report coveralls:report
  - cd struqt-unique-id && mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DapiToken= -DprojectToken=${CODACY_PROJECT_TOKEN} && cd ..
