language: java
sudo: false

jdk:
  - openjdk8
  - openjdk11

matrix:
  allow_failures:
    - jdk: openjdk11

cache:
  directories:
    - .autoconf
    - $HOME/.m2

branches:
  only:
    - master

after_success:
  - mvn clean test -Pcoveralls jacoco:report coveralls:report
  - cd struqt-unique-id && mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DapiToken= -DprojectToken=${CODACY_PROJECT_TOKEN} && cd ..
  - bash <(curl -s https://codecov.io/bash)
